version: "3.7"
services:
  nginx:
    image: nginx:1.17.8
    command: [nginx, "-g", "daemon off;"]
    volumes:
      - ./nginx_home/conf.d/:/etc/nginx/conf.d/
      - ./nginx_home/nginx.conf/:/etc/nginx/nginx.conf
      - ./home/log/:/var/log/nginx/
      - ./home/public:/var/www/html/public
    ports:
      - "80:80"
    ulimits:
      nproc: 65535
    network_mode: host
