version: "3.7"
services:
  db:
    image: postgres:12
    container_name: postgres
    ports:
      - "22224:22224"
    environment:
      POSTGRES_DB: tvc_12
      POSTGRES_USER: tvc12
      POSTGRES_PASSWORD: tvc@lovelan
      PGDATA: /var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - ./postgres.conf:/etc/postgresql.conf
      - ./home:/var/lib/postgresql/data